import { load } from "../../storage/_index.js";
import { listingsTemplate, generateBtn } from "../../templates/_index.js";
import { checkIfDeployed } from "../../tools/_index.js";

/**
 * The function loops through the given array and appends all elements generated by the listingsTemplate function to the given container.
 * It clears the HTML container before appending new elements.
 *
 * It checks the pathname and adds dispays extra elements in the DOM in regards to the current pathname:
 * - on the "profile"-page it adds H1 and an btn that links to the "userListings"-page
 * - on all except the "profile"-page it displays a pagination element
 * - on all except the "profile"-page and "userListings"-page it displays a search element
 *
 * @param {Object[]} listingsArray An array of listings passed down to the listingTemplate function
 * @param {string} container The HTML container element that listings are appended to
 *
 * @uses listingTemplate To generate a HTML element for each listing
 * @uses load To load the token from local storage and passes it to the listingTemplate function
 * @uses checkIfDeployed To check if the function is run on the deployment or local
 * @uses generateBtn To generate a button element
 */

export function renderListings(listingsArray, container) {
  const token = load("token");
  const pathname = window.location.pathname;
  container.innerHTML = "";

  if (pathname.includes("profile")) {
    const heading = document.createElement("h1");
    heading.innerText = "my latest listings";
    heading.classList.add("heading-1", "text-red", "text-center");
    container.append(heading);
  }

  for (let i = 0; i < listingsArray.length; i++) {
    container.append(listingsTemplate(listingsArray[i], token));
  }

  if (pathname.includes("profile")) {
    let link;
    const deployed = checkIfDeployed();
    if (deployed) {
      link = "../userListings/index.html";
    }
    if (!deployed) {
      link = "/userListings/index.html";
    }
    const allListingsBtn = generateBtn("userListings", "all my listings", link);
    container.append(allListingsBtn);
  }

  if (!pathname.includes("profile")) {
    const paginationElement = document.getElementById("paginationElement");
    paginationElement.style.display = "block";
  }
  if (!pathname.includes("profile") && !pathname.includes("userListings")) {
    const searchElement = document.getElementById("searchElement");
    searchElement.style.display = "block";
  }
}
